# Generated by Django 3.0.6 on 2020-05-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=20)),
                ('gender', models.CharField(default='성별', max_length=5)),
                ('phone_num', models.CharField(default='010-1234-5678', max_length=20)),
                ('email', models.CharField(default='example@example.com', max_length=30)),
                ('address', models.CharField(default='00시 00구 00대로 123', max_length=80)),
                ('insta_url', models.CharField(default='https://instagram.com/example/', max_length=80)),
                ('follower', models.CharField(default='00', max_length=30)),
                ('brand_name', models.CharField(default='default_brand', max_length=20)),
                ('keyword', models.CharField(default='default_keyword', max_length=80)),
                ('product', models.CharField(default='default_product', max_length=100)),
            ],
        ),
    ]
