# Generated by Django 3.0.6 on 2020-10-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_influencer_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer_db',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='influencer_db',
            name='brand_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='influencer_db',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='influencer_db',
            name='follower',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='influencer_db',
            name='gender',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='influencer_db',
            name='insta_url',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='influencer_db',
            name='keyword',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='influencer_db',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='influencer_db',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='influencer_db',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
