# Generated by Django 3.1.4 on 2020-12-23 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('main', '0004_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 11, 48, 40, 426254), null=True),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='회사명')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 12, 23, 11, 48, 40, 426610), null=True)),
                ('encharge_name', models.CharField(max_length=20, verbose_name='담당자명')),
                ('position', models.CharField(max_length=20, verbose_name='직책')),
                ('phone_num', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('company_address', models.TextField(verbose_name='회사 주소')),
                ('etc', models.TextField(verbose_name='특이사항')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.account')),
            ],
        ),
    ]
