# Generated by Django 3.1.4 on 2020-12-24 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201223_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 9, 34, 50, 888920), null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 9, 34, 50, 890312), null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 9, 34, 50, 889972), null=True),
        ),
    ]
