# Generated by Django 3.1.4 on 2020-12-28 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201224_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 12, 27, 26, 428723), null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 12, 27, 26, 430099), null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 12, 27, 26, 429762), null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
